# Generated by Django 5.2.3 on 2025-08-05 09:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_userblocks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserBlocks',
            new_name='UserBlock',
        ),
        migrations.RenameModel(
            old_name='UserFollows',
            new_name='UserFollow',
        ),
    ]
